cart/urls.py
from django.urls import path
from .views import (
    ItemsView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    payment_success,
    payment_failure,
    Order_tracking,
    CategoryView,
    Allproducts,
    other_items,
    search,
    ContactView,
    contact_success,
    tailoring,
    about_us,
    faqs,
    Hometest
)


app_name = 'cart'

urlpatterns = [
    path('',ItemsView.as_view(), name = 'item-list'),
    path('checkout/', CheckoutView.as_view(), name = 'checkout'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('s/', search, name = 'search'),
    path('add-to-cart/<slug>/', add_to_cart, name = 'add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name = 'remove-from-cart'),
    path('order-summary/',OrderSummaryView.as_view(), name = 'order-summary'),
    path('Allproducts', Allproducts.as_view(), name = 'Allproducts' ),
    path('other-items', other_items.as_view(), name = 'other-items'),
    path('category/<str:cats>',CategoryView, name='category'),
    path('category/Sarees',CategoryView, name='category_sarees'),
    path('category/Dress-materials', CategoryView, name='category_dresses'),
    path('category/Tops', CategoryView, name='category_tops'),
    path('category/Nighties', CategoryView, name='category_nighties'),
    path('contact',ContactView.as_view(),name='contact'),
    path('contact_success',contact_success,name='contact_success'),
    path('tailoring',tailoring,name='tailoring'),
    path('About_us',about_us,name='about_us'),
    path('FAQs',faqs,name = 'faqs'),
    path('payment_success',payment_success,name = 'payment_success'),
    path('payment_failure',payment_failure,name = 'payment_failure'),
    path('payment',PaymentView.as_view(),name = 'payment'),
    path('order_tracking',Order_tracking,name = 'order_tracking' ),

    #Testing view of Homepage
    path('hometest',Hometest, name = 'hometest')
]

cart/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

CATEGORY_CHOICES = (
    ('Sarees','Sarees'),
    ('Nighties','Nighties'),
    ('Dress materials','Dress materials'),
    ('Tops','Tops')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)

SIZE_CHOICES = (
    ('Nighties-Regular','Nighties-Regular'),
    ('Nighties-XL','Nighties-XL'),
    ('Nighties-XXL','Nighties-XXL'),
    ('Top-S','Top-S'),
    ('Top-M','Top-M'),
    ('Top-L','Top-L'),
    ('Top-XL','Top-XL'),
    ('Top-XXL','Top-XXL'),
    ('Top-XXXL','Top-XXXL')
)


class Item(models.Model):
    title = models.CharField(max_length=100,unique=True)
    image_url = models.ImageField(upload_to='media/',blank=True,null=True)
    img2 = models.ImageField(upload_to='media/',blank=True,null=True)
    img3 = models.ImageField(upload_to='media/',blank=True,null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=50)
    size = models.CharField(choices=SIZE_CHOICES,max_length=30,blank=True,null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cart:product',kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('cart:add-to-cart',kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse('cart:remove-from-cart',kwargs={
            'slug': self.slug
        })

    def get_CategoryView_url(self):
        return reverse('cart:category',kwargs={
            'cats':self.category
        })



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_final_price(self):
        if self.item.discount_price:
            return self.item.discount_price
        return self.item.price


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address',related_name='billing_address', on_delete=models.SET_NULL,blank=True,null=True)
    shipping_address = models.ForeignKey('Address',related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    personal_details = models.ForeignKey('Personaldetails',related_name='personal_details',on_delete=models.SET_NULL, blank=True, null=True)
    txnid = models.CharField(max_length=100,default='',blank=True,null=True)
    cancelled = models.BooleanField(default=False)
    cancel_refunded = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    delivery_refunded = models.BooleanField(default=False)
    amount = models.CharField(max_length=100, default='', blank=True, null=True)
    days_since_order = models.FloatField(blank=True, null=True)




    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=255)
    apartment_address = models.CharField(max_length=255)
    City = models.CharField(max_length=100)
    State = models.CharField(max_length=100)
    Pincode = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices= ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class Personaldetails(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    mobile = models.CharField(max_length=20)
    altmobile = models.CharField(max_length=20,default='', blank=True, null=True)
    email = models.EmailField()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Personal details'


class Payment(models.Model):
    txnid = models.CharField(max_length=100, default='', blank=True, null=True)
    amount = models.CharField(max_length=100, default='', blank=True, null=True)
    date_of_payment = models.CharField(max_length=100, default='', blank=True, null=True)
    name_on_card = models.CharField(max_length=100, default='', blank=True, null=True)
    cardnumber = models.CharField(max_length=100, default='', blank=True, null=True)
    bank_ref_num = models.CharField(max_length=100, default='', blank=True, null=True)
    bankcode = models.CharField(max_length=100, default='', blank=True, null=True)
    status = models.CharField(max_length=100, default='', blank=True, null=True)
    mode = models.CharField(max_length=100, default='', blank=True, null=True)
    pg_type = models.CharField(max_length=100, default='', blank=True, null=True)
    mihpayid = models.CharField(max_length=100, default='', blank=True, null=True)
    encryptedPaymentId = models.CharField(max_length=100, default='', blank=True, null=True)
    payuMoneyId = models.CharField(max_length=100, default='', blank=True, null=True)
    paid = models.BooleanField(default=False)
    refunded = models.BooleanField(default=False)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=512)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Messages'

templates/Allproducts.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Products</title>

<style>
@media only screen and (max-width: 767px){
    .col-lg-3{
        width:50%;
        height:auto;
    }

}


</style>

</head>
<body>
{% block content %}
  <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
  <link href="{% static 'css_mdbootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css_mdbootstrap/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css_mdbootstrap/style.min.css' %}" rel="stylesheet">
  <!-- Makes product cards look better -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<style>
.fa-search{
    height:4.22rem;
}
</style>



<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#" style="padding-bottom:40px;color:white;"><b>CATEGORIES</b></a>
  {% for category,a in all_categories %}
  <ul>
    <li><a href="{% url 'cart:category' category|slugify %}" style="padding-bottom:0px;padding-top:0px;">{{ category }}</a></li>
  </ul>
  {% endfor %}
</div>

<div class="row">
<!-- Use any element to open the sidenav -->
<span onclick="openNav()" class="sidebutton">&#9776;Categories</span>


<div id="main">
  <main style="">
    <div class="container">
        <h1 style="text-align:center;">Our Products</h1>
      <!--Section: Products v.3-->
      <section class="text-center mb-4">


        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                {% if item.image_url %}
                <img src="{{ item.image_url.url }}" class="card-img-top" alt="">
                {% else %}
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt="">
                {% endif %}
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                      {% if item.discount_price %}
                      {{ item.discount_price }}
                      {% else %}
                      {{ item.price }}
                      {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
        </div>
        <!--Grid row-->



      </section>
      <!-- Pagination -->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          <!--Arrow right-->
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
</div>
</div>

<script>

  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "0";
  }


  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
  }
</script>
{% endblock %}

</body>
</html>

templates/contact_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Contact Success</title>


    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Material Design Bootstrap -->
    <link href="{% static 'css_mdbootstrap/mdbnew.min.css' %}" rel="stylesheet">

    <!-- Customizer -->
    <link rel="stylesheet" href="https://mdbootstrap.com/live/_MDB/css/customizer.min.css">

    <!-- Your custom styles (optional) -->
    <link href="{% static 'css_mdbootstrap/style.css' %}" rel="stylesheet">

<style>
.success-checkmark {
  width: 80px;
  height: 115px;
  margin: 0 auto;

}
.success-checkmark .check-icon {
  width: 80px;
  height: 80px;
  position: relative;
  border-radius: 50%;
  box-sizing: content-box;
  border: 4px solid #4CAF50;
}
.success-checkmark .check-icon::before {
  top: 3px;
  left: -2px;
  width: 30px;
  transform-origin: 100% 50%;
  border-radius: 100px 0 0 100px;
}
.success-checkmark .check-icon::after {
  top: 0;
  left: 30px;
  width: 60px;
  transform-origin: 0 50%;
  border-radius: 0 100px 100px 0;
  animation: rotate-circle 4.25s ease-in;
}
.success-checkmark .check-icon::before, .success-checkmark .check-icon::after {
  content: '';
  height: 100px;
  position: absolute;
  background: #eee;
  transform: rotate(-45deg);
}
.success-checkmark .check-icon .icon-line {
  height: 5px;
  background-color: #4CAF50;
  display: block;
  border-radius: 2px;
  position: absolute;
  z-index: 10;
}
.success-checkmark .check-icon .icon-line.line-tip {
  top: 46px;
  left: 14px;
  width: 25px;
  transform: rotate(45deg);
  animation: icon-line-tip 0.75s;
}
.success-checkmark .check-icon .icon-line.line-long {
  top: 38px;
  right: 8px;
  width: 47px;
  transform: rotate(-45deg);
  animation: icon-line-long 0.75s;
}
.success-checkmark .check-icon .icon-circle {
  top: -4px;
  left: -4px;
  z-index: 10;
  width: 80px;
  height: 80px;
  border-radius: 50%;
  position: absolute;
  box-sizing: content-box;
  border: 4px solid rgba(76, 175, 80, 0.5);
}
.success-checkmark .check-icon .icon-fix {
  top: 8px;
  width: 5px;
  left: 26px;
  z-index: 1;
  height: 85px;
  position: absolute;
  transform: rotate(-45deg);
  background-color: #eee;
}
@keyframes rotate-circle {
  0% {
    transform: rotate(-45deg);
  }
  5% {
    transform: rotate(-45deg);
  }
  12% {
    transform: rotate(-405deg);
  }
  100% {
    transform: rotate(-405deg);
  }
}
@keyframes icon-line-tip {
  0% {
    width: 0;
    left: 1px;
    top: 19px;
  }
  54% {
    width: 0;
    left: 1px;
    top: 19px;
  }
  70% {
    width: 50px;
    left: -8px;
    top: 37px;
  }
  84% {
    width: 17px;
    left: 21px;
    top: 48px;
  }
  100% {
    width: 25px;
    left: 14px;
    top: 45px;
  }
}
@keyframes icon-line-long {
  0% {
    width: 0;
    right: 46px;
    top: 54px;
  }
  65% {
    width: 0;
    right: 46px;
    top: 54px;
  }
  84% {
    width: 55px;
    right: 0px;
    top: 35px;
  }
  100% {
    width: 47px;
    right: 8px;
    top: 38px;
  }
}

@media only screen and (max-width: 600px){
    .biglogo{
        display:none!important;
    }
}
</style>

</head>

<body class="fixed-sn white-skin">

<div class="success-checkmark" style="padding-top:50px;">
  <div class="check-icon">
    <span class="icon-line line-tip"></span>
    <span class="icon-line line-long"></span>
    <div class="icon-circle"></div>
    <div class="icon-fix"></div>
  </div>

</div>

<br>
<div style="text-align:center;padding-top:40px;">
    <h2>Your message has been submitted succesfully.</h2>
    <h3>We will get in touch with you shortly.</h3>
    <a href="{% url 'cart:item-list' %}" class="btn btn-secondary">Back to Home</a>
</div>

<div style="text-align:center;padding-top:60px;" class="biglogo">
    <a href="#"><img src="{% static 'img/saree_house_logo.png' %}" alt=""></a>
</div>


    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    <!-- Bootstrap dropdown -->
    <script type="text/javascript" src="{% static 'js_mdbootstrap/popper.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

    <!-- Customizer -->
    <script type="text/javascript" src="https://mdbootstrap.com/live/_MDB/js/customizer.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.1.0/jspdf.umd.min.js"></script>


</body>

</html>

templates/post_category.html
{% extends 'base.html' %}
{% load static %}
{% block products %}

<link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
<link href="{% static 'css_mdbootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
<link href="{% static 'css_mdbootstrap/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
<link href="{% static 'css_mdbootstrap/style.min.css' %}" rel="stylesheet">
  <!-- Makes product cards look better -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700|Roboto:300,400,500,700' rel='stylesheet'>

<style>
.fa-search{
    height:4.22rem;
}

.p_120 {
  padding-top: 120px;
  padding-bottom: 120px;
}

.blog_right_sidebar .tag_cloud_widget ul li {
  display: inline-block;
}

.blog_right_sidebar .tag_cloud_widget ul li a {
  display: inline-block;
  border: 1px solid #eee;
  background: #fff;
  padding: 0px 13px;
  margin-bottom: 8px;
  -webkit-transition: all 0.3s ease 0s;
  -o-transition: all 0.3s ease 0s;
  transition: all 0.3s ease 0s;
  color: #222222;
  font-size: 12px;
}

.blog_right_sidebar .tag_cloud_widget ul li a:hover {
  background: #ff2f92;
  color: #fff;
}

.blog_right_sidebar .widget_title {
  font-size: 18px;
  line-height: 25px;
  text-align: left;
  color: #222222;
  border-left: 3px solid #ff2f92;
  padding: 6px 0px 6px 13px;
  margin-bottom: 30px;
}

.list {
  list-style: none;
  margin: 0px;
  padding: 0px;
}

a:hover {
  text-decoration: none;
}

body{
    overflow-x:hidden;
}

.widget_title{
    width:150px;
}

@media only screen and (max-width: 767px){
    .widget_title{
        width:75px;
    }
}

</style>


<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#" style="padding-bottom:40px;color:white;"><b>CATEGORIES</b></a>
  {% for category,a in all_categories %}
  <ul>
    <li><a href="{% url 'cart:category' category|slugify %}" style="padding-bottom:0px;padding-top:0px;">{{ category }}</a></li>
  </ul>
  {% endfor %}
</div>

<!-- Use any element to open the sidenav -->
<!--<a href="" rel="tooltip" data-original-title="Just other tool tip data"><span onclick="openNav()" class="sidebutton">&#9776;Categories</span></a>-->
<span onclick="openNav()" class="sidebutton">&#9776;Categories</span>
<!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
<div id="main">
  <main>
    {% if size_filter_nighties %}
    <form method="POST">
        {% csrf_token %}
        <div style="float:left;width:25%;">
            <section class="blog_area p_120" style="line-height: 24px;font-size: 14px;font-family:'Open Sans', sans-serif;font-weight: normal;">
              <div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="blog_right_sidebar">
                        <aside class="tag_cloud_widget">
                            <h4 class="widget_title">Filter by Size</h4>
                            <ul class="list">
                                <li><input type="submit" name="nighties_size" value="Regular"></li>
                                <li><input type="submit" name="nighties_size" value="XL"></li>
                                <li><input type="submit" name="nighties_size" value="XXL"></li>
                                <li><a href="{% url 'cart:category' cats %}">All sizes</a></li>
                            </ul>
                        </aside>
                      </div>
                    </div>
                  </div>
              </div>
            </section>
        </div>
    </form>
    {% endif %}

    {% if size_filter_tops %}
    <form method="POST">
        {% csrf_token %}
        <div style="float:left;width:25%;">
            <section class="blog_area p_120" style="line-height: 24px;font-size: 14px;font-family:'Open Sans', sans-serif;font-weight: normal;">
              <div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="blog_right_sidebar">
                        <aside class="tag_cloud_widget">
                            <h4 class="widget_title">Filter by Size</h4>
                            <ul class="list">
                                <li><input type="submit" name="tops_size" value="S"></li>
                                <li><input type="submit" name="tops_size" value="M"></li>
                                <li><input type="submit" name="tops_size" value="L"></li>
                                <li><input type="submit" name="tops_size" value="XL"></li>
                                <li><input type="submit" name="tops_size" value="XXL"></li>
                                <li><input type="submit" name="tops_size" value="XXXL"></li>
                            </ul>
                        </aside>
                      </div>
                    </div>
                  </div>
              </div>
            </section>
        </div>
    </form>
    {% endif %}


    {% if size_filter_nighties %}
    <div>
    {% elif size_filter_tops %}
    <div>
    {% else %}
    <div class="container">
    {% endif %}
        <h1 style="text-align:center;">{{ cats }} products</h1>
        <a href="" class="seemore">View All Products</a>
      <!--Section: Products v.3-->
      <section class="text-center mb-4">


        <div class="row wow fadeIn">

          {% for item in category_products %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                {% if item.image_url %}
                <img src="{{ item.image_url.url }}" class="card-img-top" alt="">
                {% else %}
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt="">
                {% endif %}
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                      {% if item.discount_price %}
                      &#8377<!--Comment to remove whitespace-->{{ item.discount_price }}
                      {% else %}
                      &#8377<!--Comment to remove whitespace--->{{ item.price }}
                      {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}


        </div>
        <!--Grid row-->



      </section>
      <!--Section: Products v.3-->
    </div>
  </main>
</div>









<script>

  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
  }


  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
  }
</script>
{% endblock %}