cart/urls.py
from django.urls import path
from .views import (
    ItemsView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    payment_success,
    payment_failure,
    Order_tracking,
    CategoryView,
    Allproducts,
    other_items,
    search,
    ContactView,
    contact_success,
    tailoring,
    about_us,
    faqs,
    Hometest
)


app_name = 'cart'

urlpatterns = [
    path('',ItemsView.as_view(), name = 'item-list'),
    path('checkout/', CheckoutView.as_view(), name = 'checkout'),
    path('product/<slug>/', ItemDetailView.as_view(), name = 'product'),
    path('s/', search, name = 'search'),
    path('add-to-cart/<slug>/', add_to_cart, name = 'add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name = 'remove-from-cart'),
    path('order-summary/',OrderSummaryView.as_view(), name = 'order-summary'),
    path('Allproducts', Allproducts.as_view(), name = 'Allproducts' ),
    path('other-items', other_items.as_view(), name = 'other-items'),
    path('category/<str:cats>',CategoryView, name='category'),
    path('category/Sarees',CategoryView, name='category_sarees'),
    path('category/Dress-materials', CategoryView, name='category_dresses'),
    path('category/Tops', CategoryView, name='category_tops'),
    path('category/Nighties', CategoryView, name='category_nighties'),
    path('contact',ContactView.as_view(),name='contact'),
    path('contact_success',contact_success,name='contact_success'),
    path('tailoring',tailoring,name='tailoring'),
    path('About_us',about_us,name='about_us'),
    path('FAQs',faqs,name = 'faqs'),
    path('payment_success',payment_success,name = 'payment_success'),
    path('payment_failure',payment_failure,name = 'payment_failure'),
    path('payment',PaymentView.as_view(),name = 'payment'),
    path('order_tracking',Order_tracking,name = 'order_tracking' ),

    #Testing view of Homepage
    path('hometest',Hometest, name = 'hometest')
]

emailupdates/urls.py
from django.urls import path
from . import views

app_name = 'emailupdates'

urlpatterns = [
    path('signingup',views.email_subscribe, name = 'signingup'),
    path('unsigning',views.email_unsubscribe, name = 'unsigning'),
    path('banana',views.voila)

]

templates/emailupdates_gitstore/email_subscribe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Checkout Page</title>
  <!-- Font Awesome -->

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css_mdbootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css_mdbootstrap/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css_mdbootstrap/style.min.css' %}" rel="stylesheet">
</head>

<style>
@media only screen and (min-width: 768px){
    .md-form{
        left:34%;
    }
}
</style>

<body>
    <div class="container" style="padding-top:3%;width:100%;">
        <form method="POST" class="card-body" style="border:1px solid #c3c3c3;">
            <h3 class="text-center">Subscribe for latest updates</h3>
            {% csrf_token %}
            <div class="md-form">
                {{ form }}
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Subscribe</button>
                </span>
            </div>
        </form>
    </div>
    <p style="text-align:center;">If you are already a subscriber and would like to unsubscribe from our
        newsletter and updates, please <a href="{% url 'emailupdates:unsigning' %}">click here</a></p>
</body>
{% endblock %}

templates/emailupdates_gitstore/email_unsubscribe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css_mdbootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css_mdbootstrap/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css_mdbootstrap/style.min.css' %}" rel="stylesheet">

<style>
@media only screen and (min-width: 768px){
    .md-form{
        left:34%;
    }
}
</style>

<body>
    <div class="container" style="padding-top:3%;width:100%;">
        <form method="POST" class="card-body" style="border:1px solid #c3c3c3;">
            <h3 class="text-center">Unsubscribe from Sareehouse updates</h3>
            {% csrf_token %}
            <div class="md-form">
                {{ form }}
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Unsubscribe</button>
                </span>
            </div>
        </form>
    </div>
    <p style="text-align:center;">If you have not subscribed yet and would like to recieve news and updates from SareeHouse,
        please <a href="{% url 'emailupdates:signingup' %}">click here</a></p>
</body>
{% endblock %}

templates/emailupdates_gitstore/subscription_mail.html
<html>
<head>
</head>
<body>
<h2>Welcome to SareeHouse News</h2>
<p>Thank you for joining</p>
<p>To unsubscribe, click on the link: <a href='{% url "emailupdates:unsigning" %}'>Unsubscribe</a></p>
</body>
</html>

templates/emailupdates_gitstore/unsubscription_mail.html
<html>
<head>
</head>
<body>
<h2>Unsubscribed from SareeHouse updates</h2>
<p>You will not recieve updates and offers anymore from SareeHouse</p>
</body>
</html>